package com.yaxinaz.audit;

public enum AuditActionType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    USER_REGISTERED,
    MEMBERSHIP_REQUESTED,
    MEMBERSHIP_APPROVED,
    MEMBERSHIP_REJECTED,
    MEMBERSHIP_BLOCKED,
    ISSUE_CREATED,
    ISSUE_STATUS_CHANGED,
    ISSUE_PRIORITY_CHANGED,
    PROVIDER_VERIFIED,
    SERVICE_REQUEST_STATUS_CHANGED,
    CONTENT_REMOVED,
    CONTENT_REPORTED,
    CRITICAL_ALERT_CREATED
}
