package com.yaxinaz.notification;

public enum NotificationType {
    MEMBERSHIP_APPROVED,
    MEMBERSHIP_REJECTED,
    ISSUE_STATUS_UPDATED,
    ISSUE_COMMENT_ADDED,
    PROVIDER_REQUEST_ACCEPTED,
    SERVICE_REQUEST_COMPLETED,
    ANNOUNCEMENT_PUBLISHED,
    NEW_POLL,
    EVENT_REMINDER,
    CRITICAL_ALERT,
    PROVIDER_VERIFIED
}
